# IMPORTANT NOTE 
# https://github.com/chemidy/smallest-secured-golang-docker-image/issues/5

FROM golang:alpine as builder

RUN mkdir /app
ADD . /app/
WORKDIR /app

RUN chmod +x /app/*.sh
RUN sh ./install.sh
ENTRYPOINT ["sh", "./start_dev.sh"]
# ENTRYPOINT ["/bin/sh", "-c"]

EXPOSE 3000